version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - db_data:/var/lib/postgresql/data
    networks:
    - common
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    networks:
    - common
  front:
    build: front/
    ports:
    - "8082:8080"
    networks:
      - common
  back:
    build: back/
    command: poetry run hestia start_server -vvv
    networks:
      - common
volumes:
  db_data:


networks:
  common: 
    driver: 'bridge'
